frontend/controllers/LangController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\BadRequestHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * LangController implements the CRUD actions for Status model.
 */
class LangController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'switch' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['switch'],
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        // 'roles' => ['?'],
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Switches to a different language.
     * @return mixed
     */
    public function actionSwitch()
    {
        if (!Yii::$app->request->isAjax) {
            throw new BadRequestHttpException('Only AJAX request is allowed.');
        }

        Yii::info('LangController::actionSwitch():');

        $data = Yii::$app->request->post();
        Yii::info('  $data = '. print_r($data, true));

        $languageCode = $data['language'];
        Yii::info('  $languageCode = '. $languageCode);

        $oldLang = Yii::$app->language;

        $domains = Yii::$app->params['domains'];
        $newLang = $domains[$languageCode]['language'];

        Yii::info('  $domains = '. print_r($domains, true));

        $redirect = $newLang !== $oldLang;

        $url = Yii::$app->request->referrer;
        if ($redirect) {
            $oldDomain = parse_url($url, PHP_URL_HOST);
            $newDomain = $domains[$languageCode]['domain'];
            $url = str_replace($oldDomain, $newDomain, $url);
        }

        Yii::info('  $oldLang = '. $oldLang);
        Yii::info('  $newLang = '. $newLang);
        Yii::info('  $redirect = '. $redirect);
        Yii::info('  $url = '. $url);

        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return [
            'redirect' => $redirect,
            'url' => $url,
            'code' => 200,
        ];
    }
}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    $url = Url::to(['/'], true);
    $adminUrl = 'http://siteadmin' . substr($url, 9);
    NavBar::begin([
        'brandLabel' => Yii::t('app', 'My Company'),
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => Yii::t('app', 'Home'), 'url' => ['/site/index']],
        ['label' => Yii::t('app', 'About'), 'url' => ['/site/about']],
        ['label' => Yii::t('app', 'Contact'), 'url' => ['/site/contact']],
        ['label' => Yii::t('app', 'Admin'), 'url' => $adminUrl],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => Yii::t('app', 'Signup'), 'url' => ['/site/signup']];
        $menuItems[] = ['label' => Yii::t('app', 'Login'), 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                Yii::t('app', 'Logout') . ' (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <div class="container">
            <p class="pull-right">
                Language:
                <select id="language">
                    <?php
                        $domains = Yii::$app->params['domains'];
                        foreach ($domains as $key => $domain) {
                            echo '<option value="' . $key . '">' . $domain['name'] . '</option>';
                        }
                    ?>
                </select>
            </p>
        </div>
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
<script type="text/javascript">
$(function() {
    var switchLang = function(lang) {
        var csrfToken = $('meta[name="csrf-token"]').attr("content");
        $.ajax({
            url: '/lang/switch',
            type : 'POST',
            data: {language: lang, _csrf: csrfToken},
            success: function(data) {
                console.debug('/lang/switch success: data = ', data);

                if (data.redirect) {
                    window.location.href = data.url;
                }
            },
            error: function (jqXHR, textStatus, errorThrown){
                console.debug('/lang/switch error: ', errorThrown);
            },
            complete: function (jqXHR, textStatus){
                // console.debug('/lang/switch complete: textStatus = ', textStatus);
            }
        });
    }

    console.debug('language: <?php echo Yii::$app->language; ?>');
    console.debug('window.location: ', window.location);
    var currentLang = window.location.hostname.substring(0, 2);
    console.debug('currentLang: ', currentLang);
    $('#language').val(currentLang);

    $('#language').on('change', function(e) {
        e.preventDefault();
        var lang = this.value;
        console.debug('language selected: ', lang);
        // window.location.href = 'http://' + lang + window.location.href.substring(9);
        switchLang(lang);
    })
});
</script>
</body>
</html>
<?php $this->endPage() ?>